package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWebsite<M extends BaseWebsite<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer Id) {
		set("Id", Id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("Id");
	}

	public M setName(java.lang.String Name) {
		set("Name", Name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("Name");
	}

	public M setVisitorId(java.lang.Integer VisitorId) {
		set("VisitorId", VisitorId);
		return (M)this;
	}
	
	public java.lang.Integer getVisitorId() {
		return getInt("VisitorId");
	}

	public M setStatus(java.lang.Integer Status) {
		set("Status", Status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("Status");
	}

	public M setCreateTime(java.util.Date CreateTime) {
		set("CreateTime", CreateTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("CreateTime");
	}

}
