package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVisitor<M extends BaseVisitor<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer Id) {
		set("Id", Id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("Id");
	}

	public M setNAME(java.lang.String NAME) {
		set("NAME", NAME);
		return (M)this;
	}
	
	public java.lang.String getNAME() {
		return getStr("NAME");
	}

	public M setEmail(java.lang.String Email) {
		set("Email", Email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("Email");
	}

	public M setStatus(java.lang.Integer Status) {
		set("Status", Status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("Status");
	}

	public M setCreateTime(java.util.Date CreateTime) {
		set("CreateTime", CreateTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("CreateTime");
	}

}
