package com.demo.common.model;

import com.demo.common.model.base.BaseProductCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductCategory extends BaseProductCategory<ProductCategory> {
	
}
