package com.demo.common.model;

import com.demo.common.model.base.BaseUserInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserInfo extends BaseUserInfo<UserInfo> {
	
}
